fix

diff --git a/.github/workflows/test-backend.yml b/.github/workflows/test-backend.yml
--- a/.github/workflows/test-backend.yml
+++ b/.github/workflows/test-backend.yml
@@ -43,15 +43,15 @@ jobs:
     - name: Install pnpm
       uses: pnpm/action-setup@v4
     - name: Install FFmpeg
-        run: |
-          for i in {1..3}; do
-            echo "Attempt $i: Installing FFmpeg..."
-            gh run FedericoCarboni/setup-ffmpeg@v3 && break || sleep 10
-            if [ $i -eq 3 ]; then
-              echo "Failed to install FFmpeg after 3 attempts"
-              exit 1
-            fi
-          done
+      run: |
+        for i in {1..3}; do
+          echo "Attempt $i: Installing FFmpeg..."
+          gh run FedericoCarboni/setup-ffmpeg@v3 && break || sleep 10
+          if [ $i -eq 3 ]; then
+            echo "Failed to install FFmpeg after 3 attempts"
+            exit 1
+          fi
+        done
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4.0.4
       with:
